name: starter_app
description: StarterApp
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  envied: ^0.3.0+3
  equatable: ^2.0.5
  dartz: ^0.10.1
  path_provider: ^2.1.1
  logger: ^2.0.2+1
  hooks_riverpod: ^2.4.4
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.2.1
  shared_preferences: ^2.2.2
  auto_route: ^7.8.4
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.1
  dynamic_color: ^1.6.8
  easy_localization: ^3.0.3
  flutter_logs: ^2.1.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  dio: ^5.4.0





dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  custom_lint: ^0.5.4
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  flutter_flavorizr: ^2.2.1
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1


scripts: derry.yaml

flutter:
  uses-material-design: true
  # generate: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/lotties/

import_sorter:
  emojis: true # Optional, defaults to false
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/src\/[**/*.g.dart|**/*.gr.dart|**/*.freezed.dart]